# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
