# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_auto_20170201_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_field', models.TextField()),
                ('full_name', models.CharField(max_length=100)),
                ('short_about', models.TextField()),
            ],
            options={
                'db_table': 'Teachers',
            },
        ),
    ]
